targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/api/generated/swaggers'
          output_folder: 'lib/api/generated/code'
          multipart_file_type: "http.MultipartFile"
          input_urls:
            - url: "http://SpecialUser:SpecialPassword1@qa-1.filmicall.com/swagger/v1/swagger.json"
              file_name: "filmicall.json"
