targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/api/generated/swaggers'
          output_folder: 'lib/api/generated/code'
          multipart_file_type: "http.MultipartFile"
          input_urls:
            - url: "http://127.0.0.1:8000/api/openapi.json"
              file_name: "astro_class.json"
